package edu.nadn2tetris.ast;

public enum NodeKind {
    CLASS,
    CLASS_VAR_DECLARATION,
    VAR_DECLARATION,
    EXPRESSION,
    EXPRESSION_LIST,
    INTEGER_CONSTANT,
    STRING_CONSTANT,
    KEYWORD,
    ARRAY,
    SUBROUTINE_DECLARATION,
    SUBROUTINE_BODY,
    SUBROUTINE_CALL,
    PARAMETER,
    IDENTIFIER,
    OP,
    LET_STATEMENT,
    IF_STATEMENT,
    WHILE_STATEMENT,
    DO_STATEMENT,
    RETURN_STATEMENT
}
